---

- name: set creds for infoblox
  set_fact:
    nios_provider:
      username: "{{ nonprod_user }}"
      password: "{{ nonprod_password }}"
      host: "{{ nonprod_server }}"
  when: vm_env is search("np")
  tags: infoblox

- name: Remove host record requiring fqdn "{{ vm_fqdn|lower }}"
  nios_host_record:
    name: "{{ vm_fqdn|lower }}"
    state: absent
    view: default
    provider: "{{ nios_provider }}"
  tags: infoblox

- name: Remove host record that is not in dns "{{ vm_fqdn|lower }}"
  nios_host_record:
    name: "{{ vm_fqdn|lower }}"
    state: absent
    dns: false
    view: default
    provider: "{{ nios_provider }}"
  tags: infoblox

- name: Remove A record requiring "{{ vm_ip }}" and "{{ vm_fqdn|lower }}"
  nios_a_record:
    ipv4: "{{ vm_ip }}"
    name: "{{ vm_fqdn|lower }}"
    state: absent
    view: default
    provider: "{{ nios_provider }}"
  tags: infoblox

- name: Remove PTR record requiring "{{ vm_ip }}" and "{{ vm_fqdn }}"
  nios_ptr_record:
    ipv4: "{{ vm_ip }}"
    ptrdname: "{{ vm_fqdn|upper }}"
    state: absent
    view: default
    provider: "{{ nios_provider }}"
  tags: infoblox
